OnlineJudge/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings

from OJ import views
from vj import views as vjviews
handler404 = 'OJ.views.page_not_found'

urlpatterns = [
    # Examples:
    # url(r'^$', 'OnlineJudge.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^$', views.home),
    url(r'^login/$', views.login),
    url(r'^register/$', views.register),
    url(r'^logout/$', views.logout),
    url(r'^problem/$', views.problem),
    url(r'^problem/([0-9]+)/$', views.problem_detail),
    url(r'^problem/([0-9]+)/submit/$', views.problem_submit),
    url(r'^status/$', views.status),
    url(r'^contest/$', views.contest),
    url(r'^contest/([0-9]+)/$', views.contest_detail),
    url(r'^contest/([0-9]+)/get_problem$', views.contest_get_problem),
    url(r'^contest/([0-9]+)/status/$', views.contest_status),
    url(r'^contest/([0-9]+)/submit/$', views.contest_submit),
    url(r'^contest/([0-9]+)/time/$', views.contest_time),
    url(r'^contest/([0-9]+)/rank/$', views.contest_rank),
    #url(r'^contest/([0-9]+)/clar/$', views.contest_clar),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^rank/$', views.rank),
    url(r'^about/$', views.about),
    url(r'^show_source/$', views.show_source),
    url(r'^change_name/$', views.change_name),
    url(r'^profile/$', views.profile),
    #VJ folow
    url(r'^vj/$', vjviews.home),
    url(r'^vj/login/$', vjviews.login),
    url(r'^vj/accounts/login/$',vjviews.login),
    url(r'^vj/register/$', vjviews.register),
    url(r'^vj/logout/$', vjviews.logout),
    url(r'^vj/problem/$', vjviews.problem),
    url(r'^vj/problem/([0-9]+)/$', vjviews.problem_detail),
    url(r'^vj/problem/([0-9]+)/submit/$', vjviews.problem_submit),
    url(r'^vj/problem/([0-9]+)/discuss/$', vjviews.problem_discuss),
    url(r'^vj/status/$', vjviews.status),
    url(r'^vj/show_source/$', vjviews.show_source),
    url(r'^vj/admin/', admin.site.urls),
    url(r'^vj/profile/$', vjviews.profile),
    url(r'^vj/contest/$', vjviews.contest),
    url(r'^vj/contest/addcontest/$', vjviews.contest_add),
    url(r'^vj/contest/addcontest/get_problem_title/$',vjviews.addcontest_get_problem_title),
    url(r'^vj/contest/addcontest/submit/$', vjviews.contest_add_process),
    url(r'^vj/contest/([0-9]+)/$', vjviews.contest_detail),
    url(r'^vj/contest/([0-9]+)/modify/$', vjviews.contest_modify),
    url(r'^vj/contest/([0-9]+)/modify/submit/$', vjviews.contest_modify_process),
    url(r'^vj/contest/([0-9]+)/get_problem$', vjviews.contest_get_problem),
    url(r'^vj/contest/([0-9]+)/status/$', vjviews.contest_status),
    url(r'^vj/contest/([0-9]+)/submit/$', vjviews.contest_submit),
    url(r'^vj/contest/([0-9]+)/time/$', vjviews.contest_time),
    url(r'^vj/contest/([0-9]+)/rank/$', vjviews.contest_rank),
    url(r'^vj/contest/([0-9]+)/clarification/$', vjviews.contest_clarification),
    url(r'^vj/rank/$', vjviews.rank),
    url(r'^vj/about/$', vjviews.about),
]

vj/models.py
# This is an auto-generated Django model module.
# You'll have to do the following manually to clean this up:
#   * Rearrange models' order
#   * Make sure each model has one field with primary_key=True
#   * Make sure each ForeignKey has `on_delete` set to the desired behavior.
#   * Remove `managed = False` lines if you wish to allow Django to create, modify, and delete the table
# Feel free to rename the models, but don't rename db_table values or field names.
from __future__ import unicode_literals

from django.db import models
from django.contrib.auth.models import User

LANG_CHOICE = (
    (0, 'G++'),
    (1, 'GCC'),
    (2, 'C++'),
    (3, 'C'),
    (4, 'Pascal'),
    (5, 'Java'),
    (6, 'C#'),
    (7, 'Python'),
)


class Problem(models.Model):
    proid = models.AutoField(primary_key=True)
    originoj = models.CharField(max_length=10)
    problemid = models.CharField(max_length=10)
    problemurl = models.CharField(max_length=100)
    title = models.CharField(max_length=100)
    timelimit = models.CharField(max_length=50)
    memorylimit = models.CharField(max_length=50)
    description = models.TextField()
    input = models.TextField()
    output = models.TextField()
    sampleinput = models.TextField()
    sampleoutput = models.TextField()
    updatetime = models.DateTimeField()
    note = models.TextField(null=True)

    def __str__(self):
        return self.title

    def accepted(self):
        query = Status.objects.filter(pro_id=self, result= 'Accepted')
        return query.count()

    def submitted(self):
        query = Status.objects.filter(pro_id=self)
        return query.count()
    # class Meta:
    #     managed = True
    #     #db_table = 'problem'



class Discuss(models.Model):
    id=models.AutoField(primary_key=True)
    uid = models.ForeignKey(User)
    content = models.TextField()
    time=models.DateTimeField()
    proid=models.ForeignKey(Problem)

    def get_proids():
        query=Discuss.objects.all()
        return query.count()


class UserInfo(models.Model):
    id = models.OneToOneField(User, primary_key=True, related_name='vj_info')
    school = models.CharField(max_length=50, blank=True)
    sid = models.CharField(max_length=50, blank=True)
    nickname = models.CharField(max_length=50, blank=True)
    problem_ac = models.IntegerField(default = 0)
    problem_try = models.IntegerField(default = 0)
    problems_ac = models.ManyToManyField(Problem, related_name='aceduser')
    problems_try = models.ManyToManyField(Problem, related_name='trieduser')

    def __str__(self):
        return str(self.id)
    def cnt_ac(self):
        return self.problems_ac.count()
    def cnt_try(self):
        return self.problems_try.count()
    def ratio(self):
        if self.problem_try==0:
            return 0
        return int(self.problem_ac/self.problem_try*100)
    # class Meta:
    #     managed = True
    #     #db_table = 'userinfo'

class Contest(models.Model):
    uid = models.ForeignKey(User,related_name="vj_contest")
    name = models.CharField(max_length=256)
    typec = models.CharField(max_length=20,default='icpc')
    start_time = models.DateTimeField()
    duration_time = models.DurationField()
    problems = models.ManyToManyField(Problem, related_name="contests", through="Contest_problems")
    rank = models.TextField(default="{}")   #cached rank
    last_submit_id = models.IntegerField(default = 0)   #last submit id add to rank
    private = models.BooleanField(default=False)
    password = models.CharField(max_length=256,blank=True)
    accounts = models.ManyToManyField(UserInfo, related_name="accessable_contests",blank=True)
    description=models.TextField()
#    users = models.ManyToManyField(User, related_name="contests")

    def __str__(self):
        return str(self.name)

    class Meta:
        #managed = True
        ordering = ['start_time']
        # db_table = 'contest'

    def get_submits(self):
        return Submit.objects.filter(cid=self.id)

    def get_problem_list(self):
        cont_probs = Contest_problems.objects.filter(contest=self).order_by('order')
        lst = []
        cnt = 0
        for cont_prob in cont_probs:
            lst.append([cnt, chr(cnt + 65), cont_prob.problem,cont_prob.score])
            cnt += 1
        return lst

class Contest_clarification(models.Model):
    id=models.AutoField(primary_key=True)
    contest = models.ForeignKey(Contest)
    clarification = models.TextField()
    time=models.DateTimeField()

class Status(models.Model):
    runid = models.AutoField(primary_key=True)
    user = models.ForeignKey(User)
    pro = models.ForeignKey(Problem)
    source_code = models.FileField()
    lang = models.PositiveSmallIntegerField(choices=LANG_CHOICE)
    result = models.CharField(max_length=50)
    timec = models.CharField(max_length=50, blank=True, null=True)
    memoryc = models.CharField(max_length=50, blank=True, null=True)
    time = models.DateTimeField()
    cid = models.IntegerField(default=-1) 

    # class Meta:
    #     managed = True
    #     db_table = 'status'

class Contest_problems(models.Model):
    contest = models.ForeignKey(Contest)
    problem = models.ForeignKey(Problem)
    score = models.IntegerField(default=1)
    order = models.IntegerField()

templates/vj/contest/contest.html
{% extends "vj/base.html" %}

{% block title %}{{ contest.name }}{% endblock %}

{% block navbar %}{% include "vj/include/navbar-contest.html" %}{% endblock %}

{% block header %}
    <h1 class="text-center text-info">{{ contest.name }}</h1>
    <ul class="text-center" style="list-style:none;">
        <li>Start Time: {{ contest.start_time }} &nbsp;&nbsp;Duration Time: {{ contest.duration_time }}</li>
    <li id="current">Current Time: 1970-01-01 00:00:00</li>
    </ul>

<div id="current2" style="width: 0%; text-align: right; float; left;"><span></span></div>
<div class="progress">
    <div class="progress-bar progress-bar-success " role="progressbar" aria-valuenow="30" aria-valuemin="0" aria-valuemax="100" id ="progress" style="width:0%">
    </div>
</div>
<script type="text/javascript">
function getServerTime(){  
//     return new Date()
     return new Date($.ajax({async: false}).getResponseHeader("Date"));

}  
    var start;
    var duration;
    var current;
    var servertime;
    $(document).ready(function () {
         $.ajax({
             type: "post",
             url: "/vj/contest/" + {{ contest.id }} + "/time/",
             dataType: "json",
             success: function(data){
                start=new Date(data.start);
                duration=data.duration;
                syncServerTime();
                setInterval(function(){syncServerTime();},1000*60);
                setInterval(function(){refreshtime(start);},1000);
             }
         });

    });

    function str_pad_left(string,pad,length) {
        return (new Array(length+1).join(pad)+string).slice(-length);
    }

    function secondsToTime(secs)
    {
        var hours = Math.floor(secs / (60 * 60));
        var divisor_for_minutes = secs % (60 * 60);
        var minutes = Math.floor(divisor_for_minutes / 60);
        var divisor_for_seconds = divisor_for_minutes % 60;
        var seconds = Math.ceil(divisor_for_seconds);
        return hours + ":" + str_pad_left(minutes,'0',2)+':'+str_pad_left(seconds,'0',2);;
    }
    function syncServerTime(){
        servertime=getServerTime();
        current=servertime;
    }
    function refreshtime(start){
        var tmpTime = current.getTime();
        current.setTime(tmpTime+1000);
        var elapsed;
        elapsed=(current-start.getTime())/1000;
        var cutdown;
        cutdown=duration-elapsed;
        var elapsedrate;
        elapsedrate2=(elapsed/duration+0.01)*100+"%"
        elapsedrate=(elapsed/duration)*100+"%";
        var cutdowntime= secondsToTime(cutdown);
        $("#current").html("Current Time: "+current);
        if(elapsed>duration){
        $("#current2").html("<span></span>");
            $("#current2").css("width", "101%");
            $("#progress").css("width", "100%");
        } else if(elapsed<0){
            $("#current2").html("<span>-"+(secondsToTime(-elapsed))+"</span>");
            $("#current2").css("width", "1%");
            $("#progress").css("width", "0%");
        } else {
            $("#current2").html("<span>"+cutdowntime+"</span>");
            $("#current2").css("width", elapsedrate2);
            $("#progress").css("width", elapsedrate);
        } 
        if(elapsed==0){
            parent.location.reload();
        }
        



    }

</script>
{% endblock %}
{% block content %}
    <div class="tabbable" id="contest_content">
        <ul class="nav nav-tabs">
            <li class="active">
                <a data-toggle="tab" href="#panel-overview" id="overview">Overview</a>
            </li>
            <li id="Contest_Problem">
                <a data-toggle="tab" href="#panel-problem" id="problem_detail">Problem</a>
            </li>
            <li>
                <a data-toggle="tab" href="#panel-status" id="get_status">Status</a>
            </li>
            <li>
                <a data-toggle="tab" href="#panel-submit">Submit</a>
            </li>
            <li>
                <a data-toggle="tab" href="#panel-rank" id="get_rank">Rank</a>
            </li>
            <li>
                <a data-toggle="tab" href="#panel-clar" id="get_clar">Clarification</a>
            </li>

        </ul>
        <div class="tab-content">
            <div class="tab-pane active" id="panel-overview">
                {% include "vj/contest/contest_overview.html" %}
            </div>
            <div class="tab-pane" id="panel-problem">
                {% include "vj/contest/contest_problem.html" %}
            </div>
            <div class="tab-pane" id="panel-status">
                {% include "vj/contest/contest_status.html" %}
            </div>
            <div class="tab-pane" id="panel-submit">
                {% include "vj/contest/contest_submit.html" %}
            </div>
            <div class="tab-pane" id="panel-rank">
                {% include "vj/contest/contest_rank.html" %}
            </div>
            <div class="tab-pane" id="panel-clar">
                {% include "vj/contest/contest_clar.html" %}
            </div>
        </div>
    </div>
    <script type="text/javascript">
        var start;
        var duration;
        $(document).ready(function () {
        $.ajax({
            type: "post",
            url: "/vj/contest/" + {{ contest.id }} + "/time/",
            dataType: "json",
            success: function(data){
            start=new Date(data.start);
            duration=data.duration;
//               setInterval(function(){refreshtime(start);},1000);
            }
        });
        $('#get_status').click(function () {
//                alert("Hello!");
            contest_id = {{contest.id}};
            $.ajax({
                type: 'post',
                url: "/vj/contest/" + contest_id + "/status/",
                success: function (responseData) {
                    $('#panel-status').html(responseData);
        //MathJax.Hub.Queue(["Typeset", MathJax.Hub]);
                }
            })
        })
        $('#get_clar').click(function () {
            contest_id = {{contest.id}};
            $.ajax({
                type: 'post',
                url: "/vj/contest/" + contest_id + "/clarification/",
                success: function (responseData) {
                    $('#panel-clar').html(responseData);
        //MathJax.Hub.Queue(["Typeset", MathJax.Hub]);
                }
            })
        })
        $('#get_rank').click(function(){
                refreshRankList();
        })
        $('#submit_button').click(function(){
            var current=getServerTime();
            var elapsed;
            elapsed=(current-start.getTime())/1000;
            if(elapsed>duration){
                alert("Contest is Over! We will submit it in Problem for you.");
            }else{
                $('#submit_form').ajaxForm(
                    $.ajax({
                        type: 'post',
                        url: "/vj/contest/" + {{ contest.id }} + "/status/",
                        success: function (responseData) {
                            $('#panel-status').html(responseData);
                            $('#get_status').tab('show');
                        }
                        
                    })
                )
            }
        })
        /*
        $('#post_char_button').click(function(){
            var clar = $("#clar_content").val()
            if(clar == ""){
                alert("New Clarification is null!")
            }else{
                $.ajax({
                    type : "post",
                    url : "/contest/"+{{contest.id}}+"/clarification/",
                    data : {"clar":clar},
                    success : function(responseData){
                        $('#panel-clar').html(responseData)
                    }
                })
            }
        })
        */
            //$('#overview').tab('show');
        })
    </script>
{% endblock %}

templates/vj/contest/contest_add.html
{% extends "vj/base.html" %}

{% block title %}{{ contest.name }}{% endblock %}

{% block navbar %}{% include "vj/include/navbar-contest.html" %}{% endblock %}

{% block header %}
    <h1 class="text-center text-info">Add Contest</h1>
{% endblock %}
{% block content %}
    <hr>
    <script type="text/javascript">
        $(document).ready(function ()
        {
            $("#show_pass").change(function ()
            {
                if(!document.getElementById("contest_pass")){
                    $("#contest_open").after("<div class = \"row\" id=\"contest_pass\">"+
                        "<label class=\"col-sm-2 control-label\">Password:</label>"+
                        "<div class=\"col-sm-5\">"+
                        "<input type=\"password\" class=\"form-control\" name=\"password\">"+
                        "</div>"+
                        "</div>")
                }
            });
            $("#hide_pass").change(function ()
            {
                if(document.getElementById("contest_pass")){
                    $("div").remove("#contest_pass")
                }
            })
            $("#show_score").change(function()
            {
                $(".score_input").show();
            })
            $("#hide_score").change(function()
            {
                $(".score_input").hide();
            })
            
        });
        function removeTR(tdobject){
            var td=$(tdobject);  
            td.parents("tr").remove();
        }
        function addTR(){
            $("#probTable").append("<tr><td><select name=\"originoj\" class=\"form-control\" value=\"\" style=\"width:100px;\" ><option value=\"HDU\">HDU</option><option value=\"FZU\">FZU</option><option value=\"ZOJ\">ZOJ</option></select></td><td><input type=\"text\" class=\"form-control\" name=\"prob\" oninput=\"getTitle(event,this)\" onpropertychange=\"getTitle(event,this)\"></td><td><input type=\"text\" class=\"form-control\" value=\"No Such Problem\" name=\"title\" disabled=\"disabled\" style=\"width:200px;\"></td><td hidden=\"hidden\" class=\"score_input\"><input type=\"text\" class=\"form-control\"  name=\"score\" value = \"1\" style=\"width:80px;\"></td><td onclick=\"removeTR(this)\"><center><button type=\"button\" class=\"btn btn-danger\">Remove</button></center></td></tr>")
            if($("input[name='type']:checked").val() == "custom"){
                $(".score_input").show();
            }else{
                $(".score_input").hide();
            }
        }
        function getTitle(event,inputobject){
            var trobject = $(inputobject).parents("tr")
            var originoj = $(trobject).children("td").eq(0).children("select").eq(0).val()
            var probid = $(inputobject).val()
            var title_obj = $(trobject).children("td").eq(2).children("input").eq(0)
            $.ajax({
                type: 'get',
                url: "/vj/contest/addcontest/get_problem_title/?originoj=" + originoj+"&probid="+probid,
                success: function (responseData) {
                    var probid_now = $(inputobject).val()
                    if(probid == probid_now){
                        $(title_obj).val(responseData)
                    }
                }
            })
        }
        function addcontest_submit(){
            //author type openness title begin duration
            
            
            var problems = "$"
            var ok = 0

            $("#probTable tr").each(function(){
                var originoj = $(this).children("td").eq(0).children("select").eq(0).val()
                var probid   = $(this).children("td").eq(1).children("input").eq(0).val()
                var title    = $(this).children("td").eq(2).children("input").eq(0).val()
                var score    = $(this).children("td").eq(3).children("input").eq(0).val()
                if(title == "No Such Problem" || isNaN(score)){
                    //alert(title+"/"+score)
                    ok = ok + 1
                }else{
                    problems = problems + originoj + "|" + probid + "|" + score + "$"
                }
            })
            //alert(problems)
            if(ok < 2){
                
                var pass = ""
                var obj = $('input[name="password"]')
                if(obj.length != 0){
                    pass = $('input[name="password"]').val()
                }
                
                detail = {
                    "author" : $('input[name="author"]').val(),
                    "type" : $("input[name='type']:checked").val(),
                    "openness" : $("input[name='openness']:checked").val(),
                    "password" : pass,
                    "title" : $('input[name="title"]').val(),
                    "begin" : $('input[name="begin"]').val(),
                    "duration" : $('input[name="duration"]').val(),
                    "problems" : problems,
                    "description" : $('textarea[name="description"]').val()
                }
                $.ajax({
                    type : "post",
                    url : "/vj/contest/addcontest/submit/",
                    data : detail,
                    success : function(responseData){
                        if(responseData == "begin error"){
                            alert("Please check your begin-time format!")
                        }else if(responseData == "duration error"){
                            alert("Please check your duration format!")
                        }else if(responseData == "password error"){
                            alert("Please set your password!")
                        }else{
                            //alert(responseData)
                            window.location.href = responseData;
                        }
                    },
                    error : function(responseData){
                        alert("Add contest error!")
                        console.error(responseData)
                    }
                })
            }else{
                alert("Please check your problems!")
            }
            
        }
    </script>
    <div class="clearfix" style="margin-bottom: 10px;">
        <div style="width:45%;float: left;padding-left: 10px"><!-- left panel -->
            <form class="form-horizontal container-fluid">
                <div class = "row" >
                    <label class="col-sm-2 control-label">Author:</label>
                    <div class="col-sm-5">
                        <input type="text" class="form-control" style="width:200px;" name="author" value="{{user}}" disabled="disabled">
                    </div>
                </div>
                <hr>
                <div class = "row">
                    <label class="col-sm-2 control-label">Type:<font color="red">*</font></label>
                    <div class="col-md-offset-3">
                    <label>
                        <div class="radio">
                        <input type="radio" id = "hide_score" name="type" value="icpc" checked="checked"/> Standard ICPC
                        </div>
                        <div class="radio" >
                        <input type="radio" id = "show_score"  name="type" value="custom" />Customized
                        </div>
                    </label>
                    </div>
                </div>
                <hr>
                <div class = "row" id = "contest_open">
                    <label class="col-sm-2 control-label">Openness:<font color="red">*</font></label>
                    <div class="col-md-offset-3">
                    <label>
                        <div class="radio">
                        <input  type="radio" id = "hide_pass" name="openness" value="public" checked="checked"> Public
                        </div>
                        <div class="radio">
                        <input  type="radio" id = "show_pass" name="openness" value="private"> Private
                        </div>
                    </label>
                    </div>
                </div>

                <hr>
                <div class = "row">
                    <label class="col-sm-2 control-label">Title:<font color="red">*</font></label>
                    <div class="col-sm-5">
                    <input type="text" class="form-control" style="width:200px;" name="title">
                    </div>
                </div>
                <hr>
                <div class = "row">
                    <label class="col-sm-2 control-label">BeginTime:<font color="red">*</font></label>
                    <div class="col-sm-5">
                    <input type="text" class="form-control" placeholder="yyyy-MM-dd hh:mm:ss" style="width:200px;" name="begin">
                    </div>
                </div>
                <hr>
                <div class = "row">
                    <label class="col-sm-2 control-label">Duration:<font color="red">*</font></label>
                    <div class="col-sm-5">
                    <input type="text" class="form-control" placeholder="hh:mm eg: 5:00" style="width:200px;" name="duration">
                    </div>
                </div>

                <hr>
                <div class = "row">
                    <label class="col-sm-2 control-label">Description:</label>
                    <div class="col-sm-8">
                    <textarea name="description" class="form-control" maxlength="256" cols=40 rows=4 ></textarea>
                    </div>
                </div>
            </form>
        </div>
        <div style="width:45%;float: left;padding-left: 20px"><!-- right panel -->
            <div >
            <table class="table">
                <tbody id="probTable">
                    <tr>
                        <th><center>OJ</center> </th>
                        <th><center>Problem</center> </th>
                        <th><center>Title</center> </th>
                        <th hidden="hidden" class="score_input"><center>Score</center> </th>
                        <th onclick="addTR()"><center><button type = "button" class="btn btn-primary">&nbsp;&nbsp;&nbsp;Add&nbsp;&nbsp;&nbsp;</button></center></th>
                    </tr>
                    <tr>
                        <td>
                            <select name="originoj" class="form-control" value="" style="width:100px;" >
                                <option value="HDU">HDU</option>
                                <option value="FZU">FZU</option>
                                <option value="ZOJ">ZOJ</option>
                            </select>
                        </td>
                        <td >
                            <input type="text" class="form-control"  name="prob" oninput="getTitle(event,this)" onpropertychange="getTitle(event,this)">
                        </td>
                        <td>
                            <input type="text" class="form-control" value="No Such Problem" name="title" disabled="disabled" style="width:200px;"> 
                        </td>
                        <td hidden="hidden" class="score_input">
                            <input type="text" class="form-control"  name="score" style="width:80px;" value = "1">
                        </td>
                        <td onclick="removeTR(this)">
                            <center><button type="button" class="btn btn-danger">Remove</button></center>
                        </td>
                        
                    </tr>
                </tbody>
            </table>
            </div>
        </div>
        <div align="center" style="width:100%;float: right;padding-right: 20px">
                <button type="button" class="btn btn-primary" onclick="addcontest_submit()">Submit</button>
        </div>
</div>

    <hr>
{% endblock %}

templates/vj/contest/contest_status.html
</br>
<table class="table">
    <thead>
    <script type="text/javascript">
        $('#refresh_button').click(function () {
            $.ajax({
                    type: 'post',
                    url: "/vj/contest/" + {{ contest_id }} + "/status/",
                    success: function (responseData) {
                        $('#panel-status').html(responseData);
                    }
            })
        })
    </script>
    <tr>
        <th>RunID</th>
        <th>Problem</th>
        <th>Status</th>
        <th>Language</th>
        <th>User</th>
        <th>SubmitTime&nbsp;&nbsp;&nbsp;<button id = "refresh_button" class="btn btn-success">Refresh</button></th>

    </tr>
    </thead>
    <tbody>
    {% for item in status_list %}

        <tr
                {% ifequal item.result 'Waiting' %}
                    class="info"
                {% endifequal %}
                {% ifequal item.result 'Accepted' %}
                    class="success"
                {% else %}
                    class="danger"
                {% endifequal %}
         >
            <td>{{ item.runid }}</td>
            <td><a href="/vj/problem/{{ item.pro.proid}}">{{ item.pro.title }}</a></td>
            {% ifequal item.pro.isCCF True %}
                 <td>{{ item.score }}</td>
	    {% else %}
		    {% ifequal item.result "Compilation Error"%}
			<td>{{ item.result }}</td>
		    {% else %}
			<td>{{ item.result }}</td>
		    {% endifequal %}
            {% endifequal %}
            {% ifequal item.user.id user.id %}
                <td><a href="/vj/show_source?solution_id={{ item.runid }}" target="_blank">{{ item.get_lang_display }}</a></td>
            {% else %}
		    {% ifequal user.is_staff True %}
			<td><a href="/vj/show_source?solution_id={{ item.runid }}" target="_blank">{{ item.get_lang_display }}</a></td>
		    {% else %}
			<td>{{ item.get_lang_display }}</td>
		    {% endifequal %}
            {% endifequal %}
            <td>{{ item.user.username }}</td>
            <td>{{ item.time | date:"Y-m-d H:i:s" }}</td>
        </tr>
    {% endfor %}
    </tbody>
</table>
<center>
<ul class="pagination">
    <script type="text/javascript">
        //$(document).ready(function () {
        function request_contest_status(pg){
            $.ajax({
                    type: 'get',
                    url: "/vj/contest/" + {{ contest_id }} + "/status/?pg=" + pg,
                    success: function (responseData) {
                        $('#panel-status').html(responseData);
                    }
            })
        }
    </script>
    {% for id in page %}
        <li><a class="{% if pg == id %}active{% else %}disabled{% endif %}"
               href="javascript:request_contest_status({{ id }});">
            {{ id }}
            </a>
        </li>
    {% endfor %}
</ul>
</center>

templates/vj/contest/progress.html
<div style="width: 32%; text-align: right; float; left;"><span>3:30:00</span></div>
<div class="progress">
    <div class="progress-bar progress-bar-info " role="progressbar" aria-valuenow="30" aria-valuemin="0" aria-valuemax="100" style="width: 30%">
    </div>
</div>